spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:oracle:thin:@172.26.4.137:1521/XEPDB1?oracle.net.ENCODING=UTF8&oracle.net.legacyFormat=false
    username: system
    password: '123456789.'
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

file:
  storage:
    root-path: C:/rvd/uploads


# SpringDoc OpenAPI (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: false