spring.application.name=rvd
jwt.secret=esta-es-la-clave-secreta-para-el-jwt-de-rvd-universidad-de-cundinamarca
jwt.expiration=3000000

spring.servlet.multipart.max-file-size=5MB

# MAIL SERVER SECTION
mail.host=smtp.gmail.com
mail.port=587
mail.username=zebbasj@gmail.com
mail.password=fuvhheghcmgyhaad

mail.urlFront=http://localhost:4200/recover-password
mail.urlLogin=http://localhost:4200/login
